version: "3.2"

services:
    web:
        command: "debug"
        restart: "no"
        volumes:
            - ./web:/www

    mocha:
        build:
            context: ./web
            dockerfile: ./Dockerfile.test
        tty: true
        command: "test"
        volumes:
            - ./web:/www
        depends_on:
            - web
            - db
        links:
            - web
            - db
