version: "2.0"
services:
    db:
        image: mongo
        ports:
            - "27017:27017"
    web:
        build: web
        ports:
            - "3000:3000"
        links:
            - db
        depends_on:
            - db
        command: ""
        restart: on-failure
        tty: true
    front:
        build:
            context: ./web/front-end
        ports:
            - "80:80"
        depends_on:
            - db
            - web
        restart: on-failure
