version: "3.2"

services:
    db:
        image: mongo
        tty: true
        ports:
            - "27017:27017"
    web:
        build: web
        tty: true
        ports:
            - "3000:3000"
        links:
            - db
        depends_on:
            - db
        command: ""
        restart: on-failure
    front:
        build:
            context: ./web/front-end
        ports:
            - "80:80"
        depends_on:
            - db
            - web
        restart: on-failure
